sudo: required
services:
  - docker

before_install:
  - docker build -t kiranbilgundi/docker-react -f Dockerfile.dev .

script:
  - docker run kiranbilgundi/docker-react npm run test -- --coverage
  